Userlogin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from login import views
from django.contrib.auth.decorators import login_required


app_name = "login"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("login_page/", views.LoginPageView.as_view(), name="login_page"),
    path("successful_login/", login_required(views.SuccessfulLoginView.as_view()), name="successful_login"),
    path("register/", views.Registration.as_view(), name="registration"),
    path("forget_password_page/", views.ForgetPasswordView.as_view(), name="forget_password_page"),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField

class Person(models.Model):
    
    person_gender = [
        ("M", "Male"),
        ("F", "Female"),
        ("O", "Others")
    ]

    hobbies = [
        ("S", "Sports"),
        ("T", "Travelling"),
        ("R", "Reading"),
        ("P", "Painting"),
        ("w", "Writing")
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=100, choices=person_gender)
    date_of_birth = models.DateField()
    hobby = MultiSelectField(choices=hobbies)
    profie_picture = models.ImageField(upload_to='images/', null=True, blank=True)


    def __str__(self):
        return self.user.username
 

login/forms.py
from django import forms
from login.models import Person
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={"id": "password"}))
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"class": "form-control border border-2 border-dark", "placeholder": "Username"})
        self.fields["first_name"].widget.attrs.update({"class": "form-control border border-2 border-dark", "placeholder": "First Name"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control border border-2 border-dark", "placeholder": "Last Name"})
        self.fields["email"].widget.attrs.update({"class": "form-control border border-2 border-dark", "placeholder": "Email"})
        self.fields["password"].widget.attrs.update({"class": "form-control border border-2 border-dark", "placeholder": "Password"})
        self.fields["confirm_password"].widget.attrs.update({"class": "form-control border border-2 border-dark", "placeholder": "Confirm Password"})

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'confirm_password']


class PersonForm(forms.ModelForm):
    person_gender = [
        ("M", "Male"),
        ("F", "Female"),
        ("O", "Others")
    ]
    hobbies = [
        ("S", "Sports"),
        ("T", "Travelling"),
        ("R", "Reading"),
        ("P", "Painting"),
        ("w", "Writing")
    ]
    gender = forms.ChoiceField(
        widget = forms.RadioSelect,
        choices = person_gender
    )
    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={"class": "form-control border border-2 border-dark", "name": "date_of_birth", "type": "date"}) 
    )
    hobby = forms.MultipleChoiceField(
        widget = forms.CheckboxSelectMultiple(attrs={"name": "hobby"}),
        choices = hobbies
    )

    class Meta:
        model = Person
        fields = ['gender', 'date_of_birth', 'hobby', 'profie_picture']

login/views.py
from django.urls import reverse
from django.conf import settings
from login.models import Person
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from login.forms import UserForm, PersonForm
from django.views import View


class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, "login/home.html")
    

class Registration(View):
    user_form_class = UserForm
    person_form_class = PersonForm
    template_name = "login/registration.html"

    def get(self, request, *args, **kwargs):
        user_form = self.user_form_class()
        person_form = self.person_form_class()
        return render(request, self.template_name, {"user_form": user_form, "person_form": person_form})
    
    def post(self, request, *args, **kwargs):
        user_form = self.user_form_class(request.POST)
        person_form = self.person_form_class(request.POST, request.FILES)
        if user_form.is_valid() and person_form.is_valid():
            user_1 = user_form.save()

            person_1 = person_form.save(commit=False)
            person_1.user = user_1
            person_1.save()
            return HttpResponseRedirect(reverse("login:login_page"))
        
        return render(request, self.template_name, {"user_form": user_form, "person_form": person_form})


class LoginPageView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "login/login_page.html")
    
    def post(self, request, *args, **kwargs):
        user = authenticate(username=request.POST.get("username"), password=request.POST.get("password"))
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("login:successful_login"))
        else:
            context = {
                "login_failed": "Login failed. Invalid credentials"
            }
            return render(request, "login/login_page.html", context)


class SuccessfulLoginView(View):
    def get(self, request, *args, **kwargs):
        context = {
            "user": request.user,
            "user_person": request.user.person_set.first()
        }
        return render(request, "login/successful_login.html", context)
    
    def post(self, request, *args, **kwargs):
        logout(request)
        context = {
                "logout": "Logout Successful"
            }
        return render(request, "login/login_page.html", context)


class ForgetPasswordView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "login/forget_password_page.html")
    
    def post(self, request, *args, **kwargs):
        user = request.user
        if user.check_password(request.POST.get("current_password")):
            if user.check_password(request.POST.get("password")):
                context = {
                "same_password": "The new password cannot be the same as the current password"
                }
                return render(request, "login/forget_password_page.html", context)
            else:
                user.set_password(request.POST.get("password"))
                user.save()
                context = {
                "success_change_password": "Password changed successfully"
                }
                return render(request, "login/forget_password_page.html", context)
        else:
            context = {
            "fail_change_password": "Invalid Password"
            }
            return render(request, "login/forget_password_page.html", context) 

login/templates/login/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'login/CSS/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'login/CSS/signupForm.css' %}">
    <script src="{% static 'login/JS/jquery-3.7.1.min.js' %}"></script>
</head>
<body>
    {% block body %} {% endblock %}
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.min.js"></script>
<script src="{% static 'login/JS/signup_form.js' %}"></script>
</html>

login/templates/login/forget_password_page.html
{% extends "login/base.html" %}

{% load static %}

{% block title %} Change Password {% endblock %}

{% block body %} 

    {% if success_change_password %}<h3 class="text-center pt-5"><strong>{{ success_change_password }}</strong></h3>{% endif %}
    {% if same_password %}<h3 class="text-center pt-5"><strong>{{ same_password }}</strong></h3>{% endif %}
    {% if fail_change_password %}<h3 class="text-center pt-5"><strong>{{ fail_change_password }}</strong></h3>{% endif %}
    
    <form class=" py-5 cmxform col-9 m-auto" id="change_password"   method="post" autocomplete="off">
        {% csrf_token %}
        

        <div>
            <div class="input-group mt-5 mb-2">
                <span class="input-group-text border border-2 border-dark">
                    <img src="{% static 'login/Assets/lock.png' %}" class="w-100 h-100" alt="mail-logo">
                </span>
                <input type="password" id="current_password" class="form-control border border-2 border-dark" placeholder="Current Password" name="current_password">
            </div>
            <label for="current_password" class="error">Please enter your Username</label>
        </div>


        <div>
            <div class="input-group mt-5 mb-2">
                <span class="input-group-text border border-2 border-dark">
                    <img src="{% static 'login/Assets/lock.png' %}" class="w-100 h-100" alt="mail-logo">
                </span>
                <input type="password" id="password" class="form-control border border-2 border-dark" placeholder="New Password" name="password">
            </div>
            <label for="password" class="error">Please enter your Password</label>
        </div>

        
        <div>
            <div class="input-group mt-5 mb-2">
                <span class="input-group-text border border-2 border-dark">
                    <img src="{% static 'login/Assets/lock.png' %}" class="w-100 h-100" alt="mail-logo">
                </span>
                <input type="password" id="confirm_password" class="form-control border border-2 border-dark" placeholder="Confirm Password" name="confirm_password">
            </div>
            <label for="confirm_password" class="error">Password didn't match</label>
        </div>

        <div class="d-flex justify-content-center mt-5">
            <button type="submit" class="submit btn btn-success m-2" id="change_password" name="change_password">Change Password</button>
            <button type="submit" class="submit btn btn-success m-2" id="submit">
                <a href="{% url 'login:home' %}" class="text-white">Home</a>
            </button>
        </div>

    </form>
{% endblock %}

login/templates/login/home.html
{% extends "login/base.html" %}

{% load static %}

{% block title %} Home {% endblock %}

{% block body %} 
    <form class=" py-5 col-9 m-auto" method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-center mt-5 p-2">
            <a href="{% url 'login:registration' %}" class="text-white">
                <button type="button" class="submit btn btn-success" id="Sign up" name="signup">Sign up</button>
            </a>
        </div>

        <div class="d-flex justify-content-center m-2 p-2">
            <a href="{% url 'login:login_page' %}" class="text-white">
                <button type="button" class="submit btn btn-success" id="login" name="login">Login</button>
            </a>
        </div>
    </form>
{% endblock %}

login/templates/login/login_page.html
{% extends "login/base.html" %}

{% load static %}

{% block title %} Login Page {% endblock %}

{% block body %} 

    {% if login_failed %}<h3 class="text-center pt-5"><strong>{{ login_failed }}</strong></h3>{% endif %}
    {% if logout %}<h3 class="text-center pt-5"><strong>{{ logout }}</strong></h3>{% endif %}
    {% if registration_success %}<h3 class="text-center pt-5"><strong>{{ registration_success }}</strong></h3>{% endif %}

    <form method="post" class=" py-5 col-9 m-auto">
        {% csrf_token %}
        <h1 class="m-auto">Login</h1>
        <div>
            <div class="input-group mt-5 mb-2 col-6">
                <input type="text" id="username" class="form-control border border-2 border-dark" placeholder="Username" name="username">
            </div>
            <label for="username" class="error">Enter Username</label>
        </div>


        <div>
            <div class="input-group mt-5 mb-2">
                <input type="passwrod" id="password" class="form-control border border-2 border-dark" placeholder="Password" name="password">
            </div>
            <label for="passwrod" class="error">Enter Password</label>
        </div>

        <div class="d-flex justify-content-center mt-4">
            <button type="submit" class="submit btn btn-success m-2" id="submit" name="submit">Login</button>
            <a href="{% url 'login:home' %}" class="text-white">
                <button type="button" class="submit btn btn-success m-2" id="submit">Home</button>
            </a>
        </div>

    </form>
{% endblock %}

login/templates/login/registration.html
{% extends "login/base.html" %}

{% load static %}

{% block title %} Sign up Page {% endblock %}

{% block body %} 
    <div class="p-3 col-sm-6 mx-auto container my-5">
        <div class="top-line"></div>
        <div class="formbox p-5">
            
            <h1 class="text-center pt-5 mb-5">Sign Up</h1>

            {% if userexists %}<h3 class="text-center pt-5"><strong>{{ userexists }}</strong></h3>{% endif %}

            <form class=" py-5 cmxform" id="signupForm" method="post" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}

                {{ user_form.non_field_errors }}
                {{ person_form.non_field_errors }}
                <div>
                    <div>
                        {{ user_form.username.errors }}
                    </div>
                    <div class="fieldWrapper input-group mb-5">
                        <span class="input-group-text border border-2 border-dark">
                            <img src="{% static 'login/Assets/person.png' %}" class="w-100 h-100" alt="mail-logo">
                        </span>
                        {{ user_form.username }}
                    </div>
                    <label for="{{ user_form.username.id_for_label }}" class="error">Please enter your Username</label>
                </div>


                <div>
                    <div>
                        {{ user_form.first_name.errors }}
                    </div>
                    <div class="fieldWrapper input-group mb-5">
                        <span class="input-group-text border border-2 border-dark">
                            <img src="{% static 'login/Assets/person.png' %}" class="w-100 h-100" alt="mail-logo">
                        </span>
                        {{ user_form.first_name }}
                    </div>
                    <label for="{{ user_form.first_name.id_for_label }}" class="error">Please enter your First Name</label>
                </div>


                <div>
                    <div>
                        {{ user_form.last_name.errors }}
                    </div>
                    <div class="fieldWrapper input-group mb-5">
                        <span class="input-group-text border border-2 border-dark">
                            <img src="{% static 'login/Assets/person.png' %}" class="w-100 h-100" alt="mail-logo">
                        </span>
                        {{ user_form.last_name }}
                    </div>
                    <label for="{{ user_form.last_name.id_for_label }}" class="error">Please enter your Last Name</label>
                </div>


                <div>
                    <div>
                        {{ user_form.email.errors }}
                    </div>
                    <div class="error mt-3">
                    </div>
                    <div class="fieldWrapper input-group mb-5">
                        <span class="input-group-text border border-2 border-dark">
                            <img src="{% static 'login/Assets/image.png' %}" class="w-100 h-100" alt="mail-logo">
                        </span>
                        {{ user_form.email }}
                    </div>
                    <label for="{{ user_form.email.id_for_label }}" class="error">Please enter your Email</label>
                </div>


                <div>
                    <div>
                        {{ user_form.password.errors }}
                    </div>
                    <div class="fieldWrapper input-group mb-5">
                        <span class="input-group-text border border-2 border-dark">
                            <img src="{% static 'login/Assets/lock.png' %}" class="w-100 h-100" alt="mail-logo">
                        </span>
                        {{ user_form.password }}
                    </div>
                    <label for="{{ user_form.password.id_for_label }}" class="error">Please enter your Password</label>
                </div>

                
                <div>
                    <div>
                        {{ user_form.confirm_password.errors }}
                    </div>
                    <div class="fieldWrapper input-group mb-5">
                        <span class="input-group-text border border-2 border-dark">
                            <img src="{% static 'login/Assets/lock.png' %}" class="w-100 h-100" alt="mail-logo">
                        </span>
                        {{ user_form.confirm_password }}
                    </div>
                    <label for="{{ user_form.confirm_password.id_for_label }}" class="error">Please enter the same password as above</label>
                </div>


                <div>
                    <div>
                        {{ user_form.date_of_birth.errors }}
                    </div>
                    <label for="{{ person_form.date_of_birth.id_for_label }}" class="h6">Date of Birth</label>
                    <div class="input-group mt-2 mb-5">
                        {{ person_form.date_of_birth }}
                    </div>
                    <label for="date_of_birth" class="error">Please enter Date of Birth</label>
                </div>


                <fieldset>
                    <div>
                        {{ person_form.gender.errors }}
                    </div>
                    <legend class="h6 pt-2">Gender</legend>
                    <div class="form-check d-flex  py-2 mb-5">
                        {{ person_form.gender}}
                    </div>
                    <label for="gender" class="error">Please select your gender</label>
                </fieldset>


                <fieldset>
                    <div>
                        {{ person_form.hobby.errors }}
                    </div>
                    <legend class="mb-3 h6">Select your Hobbies</legend>
                    <div>
                        {{ person_form.hobby}}
                    </div>
                    <label for="hobby" class="error">Please select atleast one hobby</label>
                </fieldset>


                <fieldset>
                    <div>
                        {{ person_form.profie_picture.errors }}
                    </div>
                    <legend class="mb-3 h6">Upload profile picture</legend>
                    <div>
                        {{ person_form.profie_picture}}
                    </div>
                    <label for="hobby" class="error">Please upload an image</label>
                </fieldset>


                <div class="d-flex justify-content-center mt-5">
                    <button type="submit" class="submit btn btn-success m-2" id="submit" name="submit">Submit</button>
                    
                    <a href="{% url 'login:login_page' %}">
                        <button type="button" class="submit btn btn-success m-2" id="login" name="login">Login</button>
                    </a>
                        <a href="{% url 'login:home' %}" class="text-white">
                    <button type="button" class="submit btn btn-success m-2" id="Home">Home</button>
                        </a>
                </div>

            </form>
        </div>
    </div>

{% endblock %}

login/templates/login/successful_login.html
{% extends "login/base.html" %}

{% load static %}

{% block title %} User Account {% endblock %}

{% block body %} 

    {% if registration_success %}<h3 class="text-center pt-5"><strong>{{ registration_success }}</strong></h3>{% endif %}
    <div class="d-flex justify-content-center">
        <h1>Login Successful</h1>
    </div>
    <div class="text-center mt-5">
        <h3>Username: {{user.username}}</h3>
        <h3>Firstname: {{user.first_name}}</h3>
        <h3>Lastname: {{user.last_name}}</h3>
        <h3>Email: {{user.email}}</h3>
        <h3>Gender: {{user_person.gender}}</h3>
        <h3>Hobby: {{user_person.hobby}}</h3>
        <h3>Date of Birth: {{user_person.date_of_birth}}</h3>
    </div>
    <form class="d-flex justify-content-center" method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-center mt-5">
            <a href="{% url 'login:home' %}" class="text-white">
                <button type="button" class="submit btn btn-success m-2" id="submit">Home</button>
                
            </a>
                <button type="submit" class="submit btn btn-danger m-2" id="logout" name="logout">Logout</button>
            <a href="{% url 'login:forget_password_page' %}" class="text-white">
                <button type="button" class="submit btn btn-success m-2" id="submit">Change Password</button>
            </a>
        </div>
    </form>
{% endblock %}